/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EctMNjYhJIN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"

export function RedditPosts() {
  return (
    (<div className="flex h-screen w-full flex-col">
         <main className="flex-1 p-4 md:p-6">
          <div className="flex flex-col">
            <div className="flex items-center justify-between">
              <h2 className="text-2xl font-bold">Popular Posts</h2>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button className="flex items-center gap-1" size="sm" variant="outline">
                    <ListOrderedIcon className="h-4 w-4" />
                    <span>Sort</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuLabel>Sort by</DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>Top</DropdownMenuItem>
                  <DropdownMenuItem>New</DropdownMenuItem>
                  <DropdownMenuItem>Hot</DropdownMenuItem>
                  <DropdownMenuItem>Rising</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
            <div className="flex flex-col gap-4" >
              <div
                className="flex gap-4 rounded-md border bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950"  >
                <div className="flex flex-col items-center gap-2">
                  <Button
                    className="rounded-full p-1 text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
                    size="icon"
                    variant="ghost">
                    <ChevronUpIcon className="h-5 w-5" />
                  </Button>
                  <span className="text-sm font-medium">1.2k</span>
                  <Button
                    className="rounded-full p-1 text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
                    size="icon"
                    variant="ghost">
                    <ChevronDownIcon className="h-5 w-5" />
                  </Button>
                </div>
                <div className="flex w-full sm:w-40">
                  <img
                    alt="Post thumbnail"
                    className="rounded-md object-cover self-center "
                    height="100"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "100/100",
                      objectFit: "cover",
                    }}
                    width="100" />
                </div>
                <div className="flex flex-1 flex-col gap-2">
                  <Link className="text-lg font-medium hover:underline" href="#">
                    The Joke Tax Chronicles: How a Lazy King Tried to Tax Laughter
                  </Link>
                  <div
                    className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                    <img
                      alt="Author avatar"
                      className="rounded-full"
                      height="24"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "24/24",
                        objectFit: "cover",
                      }}
                      width="24" />
                    <span>u/shadcn</span>
                    <span>·</span>
                    <span>2 hours ago</span>
                  </div>
                  <div
                    className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                    <TextIcon className="h-4 w-4" />
                    <span>123 comments</span>
                  </div>
                </div>
              </div>
              <div
                className="flex gap-4 rounded-md border bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950">
                <div className="flex flex-col items-center gap-2">
                  <Button
                    className="rounded-full p-1 text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
                    size="icon"
                    variant="ghost">
                    <ChevronUpIcon className="h-5 w-5" />
                  </Button>
                  <span className="text-sm font-medium">850</span>
                  <Button
                    className="rounded-full p-1 text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
                    size="icon"
                    variant="ghost">
                    <ChevronDownIcon className="h-5 w-5" />
                  </Button>
                </div>
                <div className="flex w-full sm:w-40">
                  <img
                    alt="Post thumbnail"
                    className="rounded-md object-cover self-center"
                    height="100"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "100/100",
                      objectFit: "cover",
                    }}
                    width="100" />
                </div>
                <div className="flex flex-1 flex-col gap-2">
                  <Link className="text-lg font-medium hover:underline" href="#">
                    Hilarious Mishaps: A Collection of the Funniest Jokes
                  </Link>
                  <div
                    className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                    <img
                      alt="Author avatar"
                      className="rounded-full"
                      height="24"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "24/24",
                        objectFit: "cover",
                      }}
                      width="24" />
                    <span>u/colm</span>
                    <span>·</span>
                    <span>4 hours ago</span>
                  </div>
                  <div
                    className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                    <TextIcon className="h-4 w-4" />
                    <span>78 comments</span>
                  </div>
                </div>
              </div>
              <div
                className="flex gap-4 rounded-md border bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950">
                <div className="flex flex-col items-center gap-2">
                  <Button
                    className="rounded-full p-1 text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
                    size="icon"
                    variant="ghost">
                    <ChevronUpIcon className="h-5 w-5" />
                  </Button>
                  <span className="text-sm font-medium">420</span>
                  <Button
                    className="rounded-full p-1 text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-50"
                    size="icon"
                    variant="ghost">
                    <ChevronDownIcon className="h-5 w-5" />
                  </Button>
                </div>
                <div className="flex w-full sm:w-40">
                  <img
                    alt="Post thumbnail"
                    className="rounded-md object-cover self-center"
                    height="100"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "100/100",
                      objectFit: "cover",
                    }}
                    width="100" />
                </div>
                <div className="flex flex-1 flex-col gap-2">
                  <Link className="text-lg font-medium hover:underline" href="#">
                    Puns and Giggles: The Best Jokes to Tell at Parties
                  </Link>
                  <div
                    className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                    <img
                      alt="Author avatar"
                      className="rounded-full"
                      height="24"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "24/24",
                        objectFit: "cover",
                      }}
                      width="24" />
                    <span>u/pedro</span>
                    <span>·</span>
                    <span>6 hours ago</span>
                  </div>
                  <div
                    className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                    <TextIcon className="h-4 w-4" />
                    <span>42 comments</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>
    </div>)
  );
}

function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}


function ChevronUpIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m18 15-6-6-6 6" />
    </svg>)
  );
}


function CodeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>)
  );
}


function HomeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>)
  );
}


function LightbulbIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5" />
      <path d="M9 18h6" />
      <path d="M10 22h4" />
    </svg>)
  );
}


function ListOrderedIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="10" x2="21" y1="6" y2="6" />
      <line x1="10" x2="21" y1="12" y2="12" />
      <line x1="10" x2="21" y1="18" y2="18" />
      <path d="M4 6h1v4" />
      <path d="M4 10h2" />
      <path d="M6 18H4c0-1 2-2 2-3s-1-1.5-2-1" />
    </svg>)
  );
}


function ReplyAllIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="7 17 2 12 7 7" />
      <polyline points="12 17 7 12 12 7" />
      <path d="M22 18v-2a4 4 0 0 0-4-4H7" />
    </svg>)
  );
}


function RocketIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path
        d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function SmileIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M8 14s1.5 2 4 2 4-2 4-2" />
      <line x1="9" x2="9.01" y1="9" y2="9" />
      <line x1="15" x2="15.01" y1="9" y2="9" />
    </svg>)
  );
}


function TextIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M17 6.1H3" />
      <path d="M21 12.1H3" />
      <path d="M15.1 18H3" />
    </svg>)
  );
}


function TrendingUpIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="22 7 13.5 15.5 8.5 10.5 2 17" />
      <polyline points="16 7 22 7 22 13" />
    </svg>)
  );
}
