/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/o46aYzTsugV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function blogpage() {
  return (<>
    <div className="flex flex-col min-h-screen">
      <header className="bg-gray-900 text-white py-6 md:py-8 lg:py-10">
        <div className="container mx-auto px-4 md:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <img
                alt="Featured Post"
                className="rounded-lg object-cover w-full h-64 md:h-80 lg:h-96"
                height={500}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "800/500",
                  objectFit: "cover",
                }}
                width={800} />
            </div>
            <div className="flex flex-col justify-center">
              <div className="space-y-4">
                <div
                  className="inline-block bg-gray-800 px-3 py-1 rounded-full text-xs font-medium">Featured</div>
                <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold">The Future of Web Development</h1>
                <div className="flex items-center space-x-4">
                  <div className="flex items-center space-x-2">
                    <img
                      alt="Author Avatar"
                      className="rounded-full"
                      height={32}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "32/32",
                        objectFit: "cover",
                      }}
                      width={32} />
                    <span className="text-gray-400">John Doe</span>
                  </div>
                  <span className="text-gray-400">April 18, 2024</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="bg-gray-100 py-12 md:py-16 lg:py-20">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-8">Recent Posts</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <div className="bg-white rounded-lg shadow-md overflow-hidden">
                <img
                  alt="Post Thumbnail"
                  className="w-full h-48 object-cover"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600} />
                <div className="p-6">
                  <h3 className="text-xl font-bold mb-2">Mastering React: A Comprehensive Guide</h3>
                  <div className="flex items-center space-x-4 mb-4">
                    <div className="flex items-center space-x-2">
                      <img
                        alt="Author Avatar"
                        className="rounded-full"
                        height={32}
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "32/32",
                          objectFit: "cover",
                        }}
                        width={32} />
                      <span className="text-gray-500">John Doe</span>
                    </div>
                    <span className="text-gray-500">April 15, 2024</span>
                  </div>
                  <p className="text-gray-600 line-clamp-3">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl eget ultricies
                    tincidunt, nisl nisl aliquam nisl, eget aliquam nisl nisl eget nisl.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <aside className="bg-gray-900 text-white py-12 md:py-16 lg:py-20">
        <div className="container mx-auto px-4 md:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div>
              <h3 className="text-xl font-bold mb-4">Categories</h3>
              <ul className="space-y-2">
                <li>
                  <Link className="hover:underline" href="#">
                    Web Development
                  </Link>
                </li>
                <li>
                  <Link className="hover:underline" href="#">
                    Design
                  </Link>
                </li>
                <li>
                  <Link className="hover:underline" href="#">
                    Programming
                  </Link>
                </li>
                <li>
                  <Link className="hover:underline" href="#">
                    Technology
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <h3 className="text-xl font-bold mb-4">Tags</h3>
              <div className="flex flex-wrap gap-2">
                <div className="bg-gray-800 px-3 py-1 rounded-full text-xs font-medium">React</div>
                <div className="bg-gray-800 px-3 py-1 rounded-full text-xs font-medium">JavaScript</div>
                <div className="bg-gray-800 px-3 py-1 rounded-full text-xs font-medium">CSS</div>
                <div className="bg-gray-800 px-3 py-1 rounded-full text-xs font-medium">Design</div>
                <div className="bg-gray-800 px-3 py-1 rounded-full text-xs font-medium">Tutorials</div>
              </div>
            </div>
            <div>
              <h3 className="text-xl font-bold mb-4">Search</h3>
              <form className="flex items-center">
                <Input
                  className="bg-gray-800 border-none focus:ring-0 flex-1"
                  placeholder="Search blog posts..."
                  type="text" />
                <Button size="icon" type="submit" variant="ghost">
                  <SearchIcon className="h-5 w-5" />
                </Button>
              </form>
            </div>
          </div>
        </div>
      </aside>
    </div>
    <div className="flex flex-col min-h-screen">
      <main className="flex-1">
        <div className="bg-gray-900 text-white py-12 md:py-16 lg:py-20">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <img
              alt="Blog Post Hero"
              className="rounded-lg w-full h-64 md:h-80 lg:h-96 object-cover"
              height={600}
              src="/placeholder.svg"
              style={{
                aspectRatio: "1200/600",
                objectFit: "cover",
              }}
              width={1200} />
            <div className="mt-8 md:mt-12 lg:mt-16 space-y-4">
              <div
                className="inline-block bg-gray-800 px-3 py-1 rounded-full text-xs font-medium">
                Web Development
              </div>
              <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold">The Future of Web Development</h1>
              <div className="flex items-center space-x-4">
                <div className="flex items-center space-x-2">
                  <img
                    alt="Author Avatar"
                    className="rounded-full"
                    height={32}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "32/32",
                      objectFit: "cover",
                    }}
                    width={32} />
                  <span className="text-gray-400">John Doe</span>
                </div>
                <span className="text-gray-400">April 18, 2024</span>
              </div>
            </div>
          </div>
        </div>
        <div
          className="container mx-auto px-4 md:px-6 lg:px-8 py-12 md:py-16 lg:py-20">
          <div className="prose prose-lg prose-gray dark:prose-invert max-w-none">
            <h2>The Evolution of Web Development</h2>
            <p>
              Web development has come a long way since the early days of the internet. As technology continues to
              evolve, the landscape of web development is constantly changing, and it's crucial for developers to stay
              ahead of the curve.
            </p>
            <p>
              In this article, we'll explore the future of web development and discuss the trends and technologies
              that are shaping the industry. From the rise of serverless architecture to the increasing importance of
              accessibility and performance, we'll cover the key areas that developers need to focus on to stay
              competitive in the ever-changing world of web development.
            </p>
          </div>
        </div>
        <section className="bg-gray-100 py-12 md:py-16 lg:py-20">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-8">Related Posts</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <div className="bg-white rounded-lg shadow-md overflow-hidden">
                <img
                  alt="Post Thumbnail"
                  className="w-full h-48 object-cover"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600} />
                <div className="p-6">
                  <h3 className="text-xl font-bold mb-2">Mastering CSS: A Comprehensive Guide</h3>
                  <div className="flex items-center space-x-4 mb-4">
                    <div className="flex items-center space-x-2">
                      <img
                        alt="Author Avatar"
                        className="rounded-full"
                        height={32}
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "32/32",
                          objectFit: "cover",
                        }}
                        width={32} />
                      <span className="text-gray-500">Jane Doe</span>
                    </div>
                    <span className="text-gray-500">April 12, 2024</span>
                  </div>
                  <p className="text-gray-600 line-clamp-3">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl eget ultricies
                    tincidunt, nisl nisl aliquam nisl, eget aliquam nisl nisl eget nisl.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-white py-12 md:py-16 lg:py-20">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-8">Comments</h2>
            <div className="space-y-8">
              <div className="flex space-x-4">
                <img
                  alt="Author Avatar"
                  className="rounded-full"
                  height={48}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "48/48",
                    objectFit: "cover",
                  }}
                  width={48} />
                <div>
                  <h4 className="text-lg font-bold">Jane Doe</h4>
                  <p className="text-gray-600">
                    Great article! I really enjoyed learning about the future of web development. Can't wait to see
                    what's in store.
                  </p>
                  <div className="flex items-center space-x-2 mt-2">
                    <Button size="icon" variant="ghost">
                      <ThumbsUpIcon className="h-5 w-5" />
                    </Button>
                    <Button size="icon" variant="ghost">
                      <ThumbsDownIcon className="h-5 w-5" />
                    </Button>
                    <span className="text-gray-500 text-sm">2 days ago</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  </>);
}

function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function ThumbsDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M17 14V2" />
      <path
        d="M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22h0a3.13 3.13 0 0 1-3-3.88Z" />
    </svg>)
  );
}


function ThumbsUpIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M7 10v12" />
      <path
        d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>)
  );
}
