/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/yrlEajPCBFh
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"

export function facebookpostsui() {
  return (
    (<div className="flex flex-col w-full min-h-screen">
      <header
        className="bg-white dark:bg-gray-950 border-b border-gray-200 dark:border-gray-800 sticky top-0 z-10 flex items-center h-16 px-4 md:px-6">
        <Link
          className="flex items-center gap-2 text-lg font-semibold sm:text-base mr-4"
          href="#">
          <TwitterIcon className="w-6 h-6 text-[#1DA1F2]" />
          <span className="sr-only">Twitter</span>
        </Link>
        <nav
          className="hidden font-medium sm:flex flex-row items-center gap-5 text-sm lg:gap-6">
          <Link className="text-[#1DA1F2] font-bold" href="#">
            Home
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Explore
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Notifications
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Messages
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Bookmarks
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Lists
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Profile
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            More
          </Link>
        </nav>
        <div className="flex items-center w-full gap-4 md:ml-auto md:gap-2 lg:gap-4">
          <Button className="hidden sm:inline-flex" variant="primary">
            Tweet
          </Button>
          <Button className="rounded-full ml-auto" size="icon" variant="ghost">
            <img
              alt="Avatar"
              className="rounded-full border"
              height="32"
              src="/placeholder.svg"
              style={{
                aspectRatio: "32/32",
                objectFit: "cover",
              }}
              width="32" />
            <span className="sr-only">Toggle user menu</span>
          </Button>
        </div>
      </header>
      <main className="flex-1 grid grid-cols-[1fr_300px] gap-6 p-4 md:p-6">
        <div className="space-y-4">
          <div
            className="bg-white dark:bg-gray-950 rounded-lg shadow-lg overflow-hidden">
            <div className="flex items-center p-4 border-b dark:border-gray-800">
              <Avatar>
                <AvatarImage alt="Mark Zuckerberg" src="/placeholder-user.jpg" />
                <AvatarFallback>MZ</AvatarFallback>
              </Avatar>
              <div className="ml-3">
                <div className="font-semibold">Mark Zuckerberg</div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  <time dateTime="2023-04-18T12:34:56Z">18 April at 12:34</time>
                </div>
              </div>
              <div className="ml-auto">
                <Button size="icon" variant="ghost">
                  <MoreHorizontalIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                </Button>
              </div>
            </div>
            <div className="p-4">
              <p className="text-gray-800 dark:text-gray-200">
                Excited to share some big news - we're launching a new feature on Twitter that will revolutionize the
                way you connect with friends and family. Stay tuned for more details!
              </p>
              <img
                alt="Twitter post image"
                className="mt-4 rounded-lg w-full aspect-[4/3] object-cover"
                height="400"
                src="/placeholder.svg"
                width="800" />
            </div>
            <div
              className="border-t dark:border-gray-800 p-4 flex items-center justify-between">
              <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400">
                <ThumbsUpIcon className="w-5 h-5" />
                <span>1.2K</span>
              </div>
              <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400">
                <MessageCircleIcon className="w-5 h-5" />
                <span>120 comments</span>
              </div>
              <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400">
                <Share2Icon className="w-5 h-5" />
                <span>Share</span>
              </div>
            </div>
          </div>
          <div
            className="bg-white dark:bg-gray-950 rounded-lg shadow-lg overflow-hidden">
            <div className="flex items-center p-4 border-b dark:border-gray-800">
              <Avatar>
                <AvatarImage alt="Jane Doe" src="/placeholder-user.jpg" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div className="ml-3">
                <div className="font-semibold">Jane Doe</div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  <time dateTime="2023-04-17T09:12:34Z">17 April at 9:12</time>
                </div>
              </div>
              <div className="ml-auto">
                <Button size="icon" variant="ghost">
                  <MoreHorizontalIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                </Button>
              </div>
            </div>
            <div className="p-4">
              <p className="text-gray-800 dark:text-gray-200">
                Excited to share some big news - we're launching a new feature on Twitter that will revolutionize the
                way you connect with friends and family. Stay tuned for more details!
              </p>
              <img
                alt="Twitter post image"
                className="mt-4 rounded-lg w-full aspect-[4/3] object-cover"
                height="400"
                src="/placeholder.svg"
                width="800" />
            </div>
            <div
              className="border-t dark:border-gray-800 p-4 flex items-center justify-between">
              <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400">
                <ThumbsUpIcon className="w-5 h-5" />
                <span>800</span>
              </div>
              <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400">
                <MessageCircleIcon className="w-5 h-5" />
                <span>50 comments</span>
              </div>
              <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400">
                <Share2Icon className="w-5 h-5" />
                <span>Share</span>
              </div>
            </div>
          </div>
        </div>
        <div className="space-y-4">
          <div
            className="bg-white dark:bg-gray-950 rounded-lg shadow-lg overflow-hidden">
            <div className="p-4 border-b dark:border-gray-800">
              <div className="flex items-center gap-3">
                <Input
                  className="bg-gray-100 dark:bg-gray-800 rounded-full px-4 py-2 text-sm flex-1"
                  placeholder="Search Twitter"
                  type="text" />
                <Button className="rounded-full" size="icon" variant="ghost">
                  <SearchIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                </Button>
              </div>
            </div>
            <div className="p-4 space-y-4">
              <div className="flex items-center gap-3">
                <Avatar>
                  <AvatarImage alt="Trending" src="/placeholder-user.jpg" />
                  <AvatarFallback>T</AvatarFallback>
                </Avatar>
                <div className="flex-1">
                  <div className="font-semibold">Trending</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">What's happening</div>
                </div>
                <Button size="icon" variant="ghost">
                  <MoreHorizontalIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                </Button>
              </div>
              <div className="flex items-center gap-3">
                <Avatar>
                  <AvatarImage alt="News" src="/placeholder-user.jpg" />
                  <AvatarFallback>N</AvatarFallback>
                </Avatar>
                <div className="flex-1">
                  <div className="font-semibold">News</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">Stay informed</div>
                </div>
                <Button size="icon" variant="ghost">
                  <MoreHorizontalIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                </Button>
              </div>
              <div className="flex items-center gap-3">
                <Avatar>
                  <AvatarImage alt="Sports" src="/placeholder-user.jpg" />
                  <AvatarFallback>S</AvatarFallback>
                </Avatar>
                <div className="flex-1">
                  <div className="font-semibold">Sports</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">Scores, highlights, and more</div>
                </div>
                <Button size="icon" variant="ghost">
                  <MoreHorizontalIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                </Button>
              </div>
            </div>
          </div>
          <div
            className="bg-white dark:bg-gray-950 rounded-lg shadow-lg overflow-hidden">
            <div className="p-4 border-b dark:border-gray-800">
              <div className="font-semibold">Who to follow</div>
            </div>
            <div className="p-4 space-y-4">
              <div className="flex items-center gap-3">
                <Avatar>
                  <AvatarImage alt="Elon Musk" src="/placeholder-user.jpg" />
                  <AvatarFallback>EM</AvatarFallback>
                </Avatar>
                <div className="flex-1">
                  <div className="font-semibold">Elon Musk</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">@elonmusk</div>
                </div>
                <Button size="sm" variant="primary">
                  Follow
                </Button>
              </div>
              <div className="flex items-center gap-3">
                <Avatar>
                  <AvatarImage alt="Bill Gates" src="/placeholder-user.jpg" />
                  <AvatarFallback>BG</AvatarFallback>
                </Avatar>
                <div className="flex-1">
                  <div className="font-semibold">Bill Gates</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">@BillGates</div>
                </div>
                <Button size="sm" variant="primary">
                  Follow
                </Button>
              </div>
              <div className="flex items-center gap-3">
                <Avatar>
                  <AvatarImage alt="Oprah Winfrey" src="/placeholder-user.jpg" />
                  <AvatarFallback>OW</AvatarFallback>
                </Avatar>
                <div className="flex-1">
                  <div className="font-semibold">Oprah Winfrey</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">@Oprah</div>
                </div>
                <Button size="sm" variant="primary">
                  Follow
                </Button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>)
  );
}

function MessageCircleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 21 1.9-5.7a8.5 8.5 0 1 1 3.8 3.8z" />
    </svg>)
  );
}


function MoreHorizontalIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="1" />
      <circle cx="19" cy="12" r="1" />
      <circle cx="5" cy="12" r="1" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function Share2Icon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="18" cy="5" r="3" />
      <circle cx="6" cy="12" r="3" />
      <circle cx="18" cy="19" r="3" />
      <line x1="8.59" x2="15.42" y1="13.51" y2="17.49" />
      <line x1="15.41" x2="8.59" y1="6.51" y2="10.49" />
    </svg>)
  );
}


function ThumbsUpIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M7 10v12" />
      <path
        d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>)
  );
}


function TwitterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>)
  );
}
