/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/IXwhzJgeJiz
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function fullpagechips() {
  return (
    (<section className="w-full py-12">
      <div className="container grid gap-6 md:gap-8 px-4 md:px-6">
        <div
          className="flex flex-col md:flex-row items-start md:items-center gap-4 md:gap-8">
          <h1 className="text-2xl font-bold tracking-tight">Browse our sport collection</h1>
          <div className="flex flex-wrap gap-2">
            <div>Basketball</div>
            <div>Golf</div>
            <div>Soccer</div>
            <div>Running</div>
          </div>
        </div>
        <div
          className="grid md:grid-cols-2 lg:grid-cols-4 gap-4 lg:gap-6 xl:gap-8 items-start">
          <div
            className="relative group grid [grid-template-areas:stack] overflow-hidden rounded-lg">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Cover image"
              className="[grid-area:stack] object-cover w-full aspect-[3/4]"
              height={400}
              src="/placeholder.svg"
              width={300} />
            <div
              className="flex-1 [grid-area:stack] bg-black/70 group-hover:opacity-90 transition-opacity text-white p-10 justify-end flex flex-col gap-2">
              <h3 className="font-semibold text-lg tracking-tight text-center">Basketball</h3>
            </div>
          </div>
          <div
            className="relative group grid [grid-template-areas:stack] overflow-hidden rounded-lg">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Cover image"
              className="[grid-area:stack] object-cover w-full aspect-[3/4]"
              height={400}
              src="/placeholder.svg"
              width={300} />
            <div
              className="flex-1 [grid-area:stack] bg-black/70 group-hover:opacity-90 transition-opacity text-white p-10 justify-end flex flex-col gap-2">
              <h3 className="font-semibold text-lg tracking-tight text-center">Golf</h3>
            </div>
          </div>
          <div
            className="relative group grid [grid-template-areas:stack] overflow-hidden rounded-lg">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Cover image"
              className="[grid-area:stack] object-cover w-full aspect-[3/4]"
              height={400}
              src="/placeholder.svg"
              width={300} />
            <div
              className="flex-1 [grid-area:stack] bg-black/70 group-hover:opacity-90 transition-opacity text-white p-10 justify-end flex flex-col gap-2">
              <h3 className="font-semibold text-lg tracking-tight text-center">Soccer</h3>
            </div>
          </div>
          <div
            className="relative group grid [grid-template-areas:stack] overflow-hidden rounded-lg">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Cover image"
              className="[grid-area:stack] object-cover w-full aspect-[3/4]"
              height={400}
              src="/placeholder.svg"
              width={300} />
            <div
              className="flex-1 [grid-area:stack] bg-black/70 group-hover:opacity-90 transition-opacity text-white p-10 justify-end flex flex-col gap-2">
              <h3 className="font-semibold text-lg tracking-tight text-center">Running</h3>
            </div>
          </div>
        </div>
      </div>
    </section>)
  );
}
