/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YapTocDV5tF
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"

export function UploadNewVideo() {
  return (
    (<div className="grid md:grid-cols-2 gap-8 max-w-6xl mx-auto py-8 px-4">
      <div className="space-y-6">
        <div
          className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 flex flex-col items-center justify-center h-80">
          <Button size="lg" variant="outline">
            <UploadIcon className="mr-2 h-5 w-5" />
            Upload Video
          </Button>
          <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">Drag and drop a video file or click to select</p>
        </div>
        <div className="space-y-4">
          <div>
            <Label htmlFor="title">Title</Label>
            <Input id="title" placeholder="Enter a title" />
          </div>
          <div>
            <Label htmlFor="description">Description</Label>
            <Textarea id="description" placeholder="Enter a description" />
          </div>
          <div>
            <Label htmlFor="tags">Tags</Label>
            <Input id="tags" placeholder="Add tags separated by commas" />
          </div>
          <div>
            <Label htmlFor="privacy">Privacy</Label>
            <Select defaultValue="public" id="privacy">
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select privacy" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="public">Public</SelectItem>
                <SelectItem value="unlisted">Unlisted</SelectItem>
                <SelectItem value="private">Private</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      </div>
      <div className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>Video Preview</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="aspect-video rounded-lg overflow-hidden">
              <img
                alt="Video thumbnail"
                className="w-full h-full object-cover"
                height={360}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "640/360",
                  objectFit: "cover",
                }}
                width={640} />
            </div>
            <div className="mt-4 space-y-2">
              <div>
                <Label htmlFor="thumbnail">Thumbnail</Label>
                <Input id="thumbnail" type="file" />
              </div>
              <div>
                <Label htmlFor="schedule">Schedule</Label>
                <Input id="schedule" type="datetime-local" />
              </div>
              <div>
                <Label htmlFor="captions">Captions</Label>
                <Input id="captions" type="file" />
              </div>
            </div>
          </CardContent>
          <CardFooter className="flex justify-end">
            <Button>Save</Button>
          </CardFooter>
        </Card>
      </div>
    </div>)
  );
}

function UploadIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>)
  );
}
