/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XZREeCbZjQE
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { ContextMenuTrigger, ContextMenuItem, ContextMenuSeparator, ContextMenuContent, ContextMenu } from "@/components/ui/context-menu"

export function youtubewatchpage() {
  return (
    (<div
      className="w-full px-4 mx-auto grid grid-rows-[auto_1fr_auto] gap-4 md:gap-6 pb-10">
      <header>
        <div className="mx-auto h-14 flex items-center gap-4">
          <Link className="flex gap-2 font-semibold items-center" href="#">
            <YoutubeIcon className="w-8 h-8 text-red-500" />
            YouTube
          </Link>
          <div className="flex-1 ml-auto">
            <form className="max-w-sm mx-auto">
              <Input className="rounded-full" placeholder="Search" type="search" />
            </form>
          </div>
          <Avatar className="w-8 h-8 border">
            <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
            <AvatarFallback>AC</AvatarFallback>
          </Avatar>
        </div>
        <div
          className="mx-auto mt-2 flex items-center gap-2 overflow-x-auto scrollbar-hide">
          <div>All</div>
          <div>Trending</div>
          <div>Music</div>
          <div>Gaming</div>
          <div>News</div>
          <div>Sports</div>
          <div>Movies</div>
          <div>Live</div>
        </div>
      </header>
      <main className="grid md:grid-cols-6 gap-10 items-start">
        <div className="col-span-4 grid gap-4">
          <div className="grid gap-2">
            <div className="rounded-xl overflow-hidden">
              <span className="w-full aspect-video rounded-md bg-muted" />
            </div>
            <div className="py-2 grid gap-2">
              <h1 className="text-xl font-semibold line-clamp-2">
                Vercel Ship Keynote: Introducing the frontend cloud
              </h1>
              <div className="flex gap-2 items-center">
                <div className="flex gap-2 items-center">
                  <img
                    alt="Thumbnail"
                    className="rounded-full object-cover aspect-square"
                    height={40}
                    src="/placeholder.svg"
                    width={40} />
                  <div className="text-sm">
                    <div className="font-semibold">Vercel</div>
                    <div className="text-xs text-gray-500 dark:text-gray-400">70K subscribers</div>
                  </div>
                </div>
                <div className="ml-auto">
                  <Button variant="outline">Subscribe</Button>
                </div>
              </div>
            </div>
            <div className="bg-gray-100 rounded-xl p-4 text-sm dark:bg-gray-800">
              <p>
                Today, we're introducing the frontend cloud, where frontend developers build, test, and deploy
                high-quality web applications efficiently and quickly, all on Vercel.
              </p>
            </div>
          </div>
          <div className="grid gap-6">
            <h2 className="font-semibold text-xl">110 Comments</h2>
            <div className="text-sm flex items-start gap-4">
              <Avatar className="w-10 h-10 border">
                <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <div className="grid gap-1.5">
                <div className="flex items-center gap-2">
                  <div className="font-semibold">@iamwillpursell</div>
                  <div className="text-gray-500 text-xs dark:text-gray-400">5 months ago</div>
                </div>
                <div>
                  I really love the ecosystem Vercel is creating. The way each component can be added and modified with
                  ease really makes these tools attractive.
                </div>
              </div>
            </div>
            <div className="text-sm flex items-start gap-4">
              <Avatar className="w-10 h-10 border">
                <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <div className="grid gap-1.5">
                <div className="flex items-center gap-2">
                  <div className="font-semibold">@HackSoft</div>
                  <div className="text-gray-500 text-xs dark:text-gray-400">2 months ago</div>
                </div>
                <div>
                  We are more than excited to leverage all the new stuff, building better products for our clients ✨
                </div>
              </div>
            </div>
            <div className="text-sm flex items-start gap-4">
              <Avatar className="w-10 h-10 border">
                <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <div className="grid gap-1.5">
                <div className="flex items-center gap-2">
                  <div className="font-semibold">@greed7513</div>
                  <div className="text-gray-500 text-xs dark:text-gray-400">6 days ago</div>
                </div>
                <div>does anyone know which monospace are they using when showing code?</div>
              </div>
            </div>
          </div>
        </div>
        <div className="col-span-2 grid gap-4">
          <div className="flex items-start gap-4 relative">
            <Link className="absolute inset-0" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Thumbnail"
              className="aspect-video rounded-lg object-cover"
              height={94}
              src="/placeholder.svg"
              width={168} />
            <div className="text-sm">
              <div className="font-medium line-clamp-2">Introducing v0: Generative UI</div>
              <div className="text-xs text-gray-500 line-clamp-1 dark:text-gray-400">Vercel</div>
              <div className="text-xs text-gray-500 line-clamp-1 dark:text-gray-400">300K views · 5 days ago</div>
            </div>
          </div>
          <div className="flex items-start gap-4 relative">
            <Link className="absolute inset-0" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Thumbnail"
              className="aspect-video rounded-lg object-cover"
              height={94}
              src="/placeholder.svg"
              width={168} />
            <div className="text-sm">
              <div className="font-medium line-clamp-2">Introducing the frontend cloud</div>
              <div className="text-xs text-gray-500 line-clamp-1 dark:text-gray-400">Vercel</div>
              <div className="text-xs text-gray-500 line-clamp-1 dark:text-gray-400">1.2M views · 2 months ago</div>
            </div>
          </div>
          <div className="flex items-start gap-4 relative">
            <Link className="absolute inset-0" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Thumbnail"
              className="aspect-video rounded-lg object-cover"
              height={94}
              src="/placeholder.svg"
              width={168} />
            <div className="text-sm">
              <div className="font-medium line-clamp-2">Using Vercel KV with Svelte</div>
              <div className="text-xs text-gray-500 line-clamp-1 dark:text-gray-400">Lee Robinson</div>
              <div className="text-xs text-gray-500 line-clamp-1 dark:text-gray-400">21K views · 1 week ago</div>
            </div>
          </div>
          <div className="flex items-start gap-4 relative">
            <Link className="absolute inset-0" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Thumbnail"
              className="aspect-video rounded-lg object-cover"
              height={94}
              src="/placeholder.svg"
              width={168} />
            <div className="text-sm">
              <div className="font-medium line-clamp-2">Loading UI with Next.js 13</div>
              <div className="text-xs text-gray-500 line-clamp-1 dark:text-gray-400">Delba</div>
              <div className="text-xs text-gray-500 line-clamp-1 dark:text-gray-400">12K views · 10 days ago</div>
            </div>
          </div>
          <div className="flex items-start gap-4 relative">
            <Link className="absolute inset-0" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Thumbnail"
              className="aspect-video rounded-lg object-cover"
              height={94}
              src="/placeholder.svg"
              width={168} />
            <div className="text-sm">
              <div className="font-medium line-clamp-2">Shorts: Introducing the frontend cloud</div>
              <div className="text-xs text-gray-500 line-clamp-1 dark:text-gray-400">Vercel</div>
              <div className="text-xs text-gray-500 line-clamp-1 dark:text-gray-400">500K views · 1 day ago</div>
            </div>
          </div>
          <div className="flex items-start gap-4 relative">
            <Link className="absolute inset-0" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Thumbnail"
              className="aspect-video rounded-lg object-cover"
              height={94}
              src="/placeholder.svg"
              width={168} />
            <div className="text-sm">
              <div className="font-medium line-clamp-2">Shorts: Vercel Ship Keynote</div>
              <div className="text-xs text-gray-500 line-clamp-1 dark:text-gray-400">Vercel</div>
              <div className="text-xs text-gray-500 line-clamp-1 dark:text-gray-400">800K views · 3 days ago</div>
            </div>
          </div>
        </div>
      </main>
      <ContextMenu>
        <ContextMenuTrigger
          className="fixed bottom-4 right-4 bg-white dark:bg-gray-900 rounded-full p-2 shadow-lg">
          <MoreHorizontalIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
        </ContextMenuTrigger>
        <ContextMenuContent className="w-48">
          <ContextMenuItem>
            <HomeIcon className="w-4 h-4 mr-2" />
            Home
          </ContextMenuItem>
          <ContextMenuItem>
            <TrendingUpIcon className="w-4 h-4 mr-2" />
            Trending
          </ContextMenuItem>
          <ContextMenuItem>
            <SubscriptIcon className="w-4 h-4 mr-2" />
            Subscriptions
          </ContextMenuItem>
          <ContextMenuSeparator />
          <ContextMenuItem>
            <LibraryIcon className="w-4 h-4 mr-2" />
            Library
          </ContextMenuItem>
          <ContextMenuItem>
            <HistoryIcon className="w-4 h-4 mr-2" />
            History
          </ContextMenuItem>
          <ContextMenuItem>
            <WatchIcon className="w-4 h-4 mr-2" />
            Watch later
          </ContextMenuItem>
          <ContextMenuSeparator />
          <ContextMenuItem>
            <SettingsIcon className="w-4 h-4 mr-2" />
            Settings
          </ContextMenuItem>
          <ContextMenuItem>
            <HelpCircleIcon className="w-4 h-4 mr-2" />
            Help
          </ContextMenuItem>
          <ContextMenuItem>
            <ReplyIcon className="w-4 h-4 mr-2" />
            Feedback
          </ContextMenuItem>
        </ContextMenuContent>
      </ContextMenu>
    </div>)
  );
}

function HelpCircleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
      <path d="M12 17h.01" />
    </svg>)
  );
}


function HistoryIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" />
      <path d="M3 3v5h5" />
      <path d="M12 7v5l4 2" />
    </svg>)
  );
}


function HomeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>)
  );
}


function LibraryIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m16 6 4 14" />
      <path d="M12 6v14" />
      <path d="M8 8v12" />
      <path d="M4 4v16" />
    </svg>)
  );
}


function MoreHorizontalIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="1" />
      <circle cx="19" cy="12" r="1" />
      <circle cx="5" cy="12" r="1" />
    </svg>)
  );
}


function ReplyIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="9 17 4 12 9 7" />
      <path d="M20 18v-2a4 4 0 0 0-4-4H4" />
    </svg>)
  );
}


function SettingsIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>)
  );
}


function SubscriptIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m4 5 8 8" />
      <path d="m12 5-8 8" />
      <path
        d="M20 19h-4c0-1.5.44-2 1.5-2.5S20 15.33 20 14c0-.47-.17-.93-.48-1.29a2.11 2.11 0 0 0-2.62-.44c-.42.24-.74.62-.9 1.07" />
    </svg>)
  );
}


function TrendingUpIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="22 7 13.5 15.5 8.5 10.5 2 17" />
      <polyline points="16 7 22 7 22 13" />
    </svg>)
  );
}


function WatchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="6" />
      <polyline points="12 10 12 12 13 13" />
      <path
        d="m16.13 7.66-.81-4.05a2 2 0 0 0-2-1.61h-2.68a2 2 0 0 0-2 1.61l-.78 4.05" />
      <path d="m7.88 16.36.8 4a2 2 0 0 0 2 1.61h2.72a2 2 0 0 0 2-1.61l.81-4.05" />
    </svg>)
  );
}


function YoutubeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>)
  );
}
