/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2Kz95qSMYnd
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import VideoTable from "./VideoTable";

export function StudioPage() {
  return (
          <div className="border rounded-lg overflow-auto ">
            <VideoTable/>
          </div>
  );
}


