/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/gOwbMMwoLD0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import getUserDetails from "./funcs/getUserDetails";
import { getUserSession } from "@/lib/sessions";

export async function UserSettingsPage() {

    let id = await getUserSession();
    id = id.id;
    let user = await getUserDetails(id);
  return (
    (<main className="w-full max-w-3xl mx-auto py-12 px-4 md:px-6">
      <header className="mb-8">
        <h1 className="text-3xl font-bold">Account Settings</h1>
      </header>
      {
        // Profile Image, Username, Full Name, Email Address
      }
      <form className="space-y-6">
        <div className="space-y-2">
          <Label htmlFor="profileImage">Profile Image</Label>
          <div className="flex items-center gap-4">
            <Avatar className="h-16 w-16">
              <AvatarImage alt="Profile Image" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JP</AvatarFallback>
            </Avatar>
            <Input id="profileImage" type="file" />
          </div>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          <div className="space-y-2">
            <Label htmlFor="username">Username</Label>
            <Input id="username" placeholder="Enter your username" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="fullName">Full Name</Label>
            <Input id="fullName" placeholder="Enter your full name" />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="email">Email Address</Label>
          <Input id="email" placeholder="Enter your email address" type="email" />
        </div>
        <div className="flex justify-end">
          <Button className="ml-auto" type="submit">
            Save Changes
          </Button>
        </div>
      </form>
    </main>)
  );
}
